- name: install nginx
  hosts: nginx
  become: true
  tasks:
    - name: apt install nginx
      apt:
        name: nginx
    - name: port change to 8090
      lineinfile:
        path: /etc/nginx/sites-enabled/default
        search_string: 'listen 80 default_server;'
        line: listen 8090 default_server;
    - name: proxy pass to nodejs app
      lineinfile:
        path: /etc/nginx/sites-enabled/default
        insertafter: 'then fall back to displaying'
        line: proxy_pass http://54.237.173.211:8080;
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
    - name: customed html file
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        search_string: 'Welcome to nginx'
        line: <h1>Welcome to Ansible Task_1 on Nginx-Server!</h1>
- name: install nodejs app
  hosts: nodejs
  become: true
  tasks:
    - name: copy nodejs files
      copy:
        src: ./nodejsapp/
        dest: /home/ubuntu
    - name: apt install npm
      apt:
        name: npm
        update_cache: true   
    - name: run server
      shell: |
        npm install
        node server.js