# Generated by Django 4.2.1 on 2023-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_student_birth_date_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_id', models.CharField(max_length=255, null=True)),
                ('c_start_date', models.DateField(null=True)),
                ('c_end_date', models.DateField(null=True)),
            ],
        ),
    ]
