# Generated by Django 4.2.1 on 2023-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_student_birth_date_alter_student_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l_name',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='text',
            field=models.TextField(default='Type text here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
